# Generated by Django 4.2.16 on 2024-11-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0002_keyvalue_created_at_alter_keyvalue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyvalue',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
